// scripts/live-test.ts
// Send ONE test email to ricomiller@icloud.com through the production send path.
// Verifies: sender identity, Gmail auth, CRM logging, label creation.
// Usage: npx tsx scripts/live-test.ts

import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

import { isAuthConfigured, checkSendAsAlias } from "../lib/gmail/auth";
import { validateSendReadiness, sendEmail, resetRunCounter } from "../lib/gmail/sender";
import { query } from "../lib/db";

const TEST_TARGET = process.env.OWNER_EMAIL ?? "ricomiller@icloud.com";
const SEND_AS = process.env.SEND_AS_EMAIL ?? "ricomiller@icloud.com";

async function main() {
  console.log("\n" + "═".repeat(60));
  console.log("LIVE SEND TEST");
  console.log("═".repeat(60));

  // Step 1: Auth check
  console.log("\n[1] Checking Gmail authentication...");
  if (!isAuthConfigured()) {
    console.error("❌ Gmail credentials not configured.");
    console.error("   Run: npx tsx scripts/setup-gmail.ts");
    process.exit(1);
  }
  console.log("   ✅ Credentials present");

  // Step 2: Alias check
  console.log(`\n[2] Checking send-as alias: ${SEND_AS}`);
  const aliasStatus = await checkSendAsAlias(SEND_AS);
  if (aliasStatus.error) {
    console.error(`❌ Gmail API error: ${aliasStatus.error}`);
    process.exit(1);
  }
  if (!aliasStatus.found) {
    console.error(`❌ ${SEND_AS} is NOT configured as a send-as alias.`);
    console.error(`   Configured aliases: ${aliasStatus.allAliases.join(", ") || "(none)"}`);
    console.error(`\n   FIX: Gmail → Settings → Accounts and Import → Send mail as → Add ${SEND_AS}`);
    process.exit(1);
  }
  if (!aliasStatus.verified) {
    console.error(`❌ ${SEND_AS} found but not verified. Check ${SEND_AS} for a verification email.`);
    process.exit(1);
  }
  console.log(`   ✅ ${SEND_AS} is configured and verified`);

  // Step 3: Send test email
  const subject = `[TEST] Filings Outreach — Identity Verification`;
  const body = `This is a test email from the Filings Outreach automation system.

If you received this, it confirms:
  ✅ Gmail authentication is working
  ✅ From identity: ${SEND_AS} (ricomiller@icloud.com)
  ✅ Production send path is functional

Sent via: AntiGravity Filings Outreach System
Time: ${new Date().toISOString()}

Rico Miller
${SEND_AS}`;

  console.log(`\n[3] Sending test email to ${TEST_TARGET}...`);
  resetRunCounter();
  const result = await sendEmail({
    to: TEST_TARGET,
    subject,
    body,
    isTest: true,
  });

  if (!result.success) {
    console.error(`❌ Send failed: ${result.error}`);
    process.exit(1);
  }

  console.log(`   ✅ Email sent! Message ID: ${result.messageId}`);
  console.log(`   Thread ID: ${result.threadId}`);

  // Step 4: Log to CRM
  console.log("\n[4] Writing test record to outreach_crm...");
  await query(
    `INSERT INTO outreach_crm (
       target_company, contact_person, email, issuer_name, filing_date,
       email_subject, email_body, sent_at, gmail_message_id, gmail_thread_id,
       delivery_status, reply_status, notes, owner
     ) VALUES (
       'TEST', 'Self-Test', $1, 'TEST-SYSTEM', CURRENT_DATE,
       $2, $3, NOW(), $4, $5,
       'sent', 'awaiting', 'test email — auto-generated by live-test.ts', 'ricomiller@icloud.com'
     )`,
    [TEST_TARGET, subject, body, result.messageId ?? null, result.threadId ?? null]
  );
  console.log("   ✅ CRM record written");

  console.log(`\n${"═".repeat(60)}`);
  console.log("✅ ALL TESTS PASSED");
  console.log(`\n   Check ${TEST_TARGET} for the test email.`);
  console.log("   Verify the From address shows as: ricomiller@icloud.com");
  console.log("   Check Gmail for label: AntiGravity/Filings-Outreach");
  console.log(`${"═".repeat(60)}\n`);

  process.exit(0);
}

main().catch((e) => {
  console.error("❌ Live test failed:", e.message);
  process.exit(1);
});
